spring:
    application:
        name: chat-service
    profiles:
        active: local
server:
    port: ${SERVER_PORT:8081}
    servlet:
        context-path: ${CONTEXT_PATH:/chat-service}
app:
    ollama:
        chat-model:
            base-url: http://localhost:11434
            model-name: gemma4:31b
#            model-name: gpt-oss:20b
