create table if not exists orders (
    id bigint generated by default as identity primary key,
    carrier varchar(255),
    current_location varchar(255),
    customer_name varchar(255) not null,
    estimated_delivery_date date,
    item_name varchar(255) not null,
    order_date date,
    order_number varchar(255) not null constraint unique,
    quantity integer,
    status varchar(255) not null,
    total_amount numeric(38, 2),
    tracking_number varchar(255),
    delivery_address varchar(255),
    cancellation_reason varchar(255)
);