spring:
    application:
        name: credit-rating-service
    profiles:
        active: local
server:
    port: ${SERVER_PORT:8082}
    servlet:
        context-path: ${CONTEXT_PATH:/credit-rating-service}