spring:
    application:
        name: loan-service
    profiles:
        active: local
server:
    port: ${SERVER_PORT:8081}
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/